apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ray-test
spec:
  url: https://github.com//utsavv27/testing-1
  interval: 5m
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kust
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./Ray-llm
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: ray-test
  # targetNamespace: default
  timeout: 3m0s
  wait: true